### ISSUE TITLE
cannot hide in swift project

### ISSUE THREAD

**Issue by longxianlin** [ask-fm/AFMInfoBanner#6]
cannot hide

**Comment by karpelcevs** [comment]
Hi! Can you please explain the issue in more details? What is your setup and what is (and isn't happening)?
If you can, a example project would be very useful too.

**Comment by longxianlin** [comment]
sorry, it's my problem in my project. I just make a new project, it work.
https://github.com/longxianlin/Demos/tree/master/AFMInfoBannerInSwift

**Comment by longxianlin** [comment]
it work in new project.

but not working in my project. I am searching the bug.
